services:
  # mongo:
  #   image: mongo:7.0
  #   container_name: sablier-mongo
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-admin123}
  #     MONGO_INITDB_DATABASE: sablier-db
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - app-network
  #   healthcheck:
  #     test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sablier-frontend
    restart: unless-stopped
    environment:
      - DB_NAME=${DB_NAME:-crud-app}
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@host.docker.internal:53169?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-this}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - HOST=0.0.0.0
      - PORT=4321
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   mongo:
    #     condition: service_healthy
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: sablier-nginx
    restart: unless-stopped
    ports:
      - "8085:80"  # Expose nginx on port 8080, change as needed
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - app-network

# volumes:
#   mongo_data:
#     driver: local

networks:
  app-network:
    driver: bridge