services:
  frontend:
    build: .
    ports:
      - "4321:4321"
    environment:
      # - MONGODB_URI=mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-admin123}@host.docker.internal:27017/sablier-db?authSource=admin
      - MONGODB_URI=mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-admin123}@mongo:27017/sablier-db?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-this}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-admin123}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge